classDiagram
    割合パイ --> SharePie
    金額パイ --> SharePie
    SharePie --* シェア

    class SharePie["シェアパイ"] {
        SortedSet~シェア~ 配分構成
        [制約：企業が重複しない]
        [制約：分担量の大きい順]
        端数の調整(正しい全体量) シェアパイ
        掛ける(倍数) シェアパイ
        割る(除数) シェアパイ
    }

    class シェア {
        企業 String
        分担量 int
        掛ける(倍数) シェア
        割る(除数) シェア
        増やす(増分) シェア
        同一企業(比較対象のシェア) boolean
    }