---
title: 業務の関心事
---
classDiagram
    class 配分金額 {
        シェアパイ
        [制約：端数は最大出資者に配分]
        合算(金額構成) 金額構成
        差分(金額構成) 金額構成
    }
    class 配分比率 {
        シェアパイ
        スケール 万分率
        [制約：合計が100%になること]
        比例配分する(対象金額) 金額構成
    }

