classDiagram
    貸付枠 --> 割合パイ
    貸付 --> 金額パイ
    class 貸付枠 {
        限度額
        移動(企業, 企業, 移動量) : 貸付枠
    }

    class 貸付 {
        総額
        増額(金額) 貸付
        減額(金額) 貸付
        端数調整() 貸付
    }

    class 金額パイ {
        シェアパイ
        [制約：端数は最大出資者に配分]
        合算(金額構成) 金額構成
        差分(金額構成) 金額構成
    }
    class 割合パイ {
        シェアパイ
        スケール 万分率
        [制約：合計が100%になること]
        比例配分する(対象金額) 金額構成
    }

