classDiagram
    貸付枠 --> 割合パイ
    貸付 --> 金額パイ
    割合パイ --> シェアパイ
    金額パイ --> シェアパイ
    シェアパイ --* シェア

    namespace 業務の関心事 {
        class 貸付枠 {
            限度額
        }
        class 貸付 {
            総額
        }
        class 割合パイ {
            シェアパイ 分担比率
        }
        class 金額パイ {
            シェアパイ　分担金額
        }
    }
