classDiagram
    direction LR
    メンバー経験言語 --> メンバー
    メンバー経験言語 --> 言語セット
    言語セット --* 言語

    class メンバー経験言語 {
        メンバー
        言語セット
    }

    class 言語セット {
        Set~言語~
        一致した言語セット(対象の言語セット) 言語セット
    }

    class 言語 {
        <<列挙>>
        Python,
        Java,
        CPlusPlus,
        CSharp,
        JavaScript,
        SQL,
        PHP,
        GO,
        Rust
    }